### ISSUE TITLE
Batch PRs based on labels

### ISSUE THREAD

**Issue by rosstimothy** [Legal-and-General/dependabot-batcher#102]
## Batch PRs based on labels

This feature request affects:

* [ ] GitHub workflows
* [ X ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

Add a configuration option to limit batching Dependabot PRs that have specific label(s).

## Motivation

A monorepo may have both frontend and backend code which causes Dependabot to create PRs with labels per language: `go`, `rust`, `java`, `javascript`, etc. Allowing users to configure the batcher to group based on a set of labels allows for greater control of how and when certain Dependabot PRs get merged. 

## Describe alternatives you've considered

It is possible to schedule updates and the batcher to run at different times of the week. Assuming the prior PR gets merged before the next Dependabot and Batcher workflows run this can work but isn't very flexible.

**Comment by pauleustice** [comment]
@rosstimothy So sorry for the late reply to this. This sounds like a sensible suggestion and should be straightforward to implement; would you mind validating what I believe you're asking for?

- Dependabot Batcher supports filtering the Dependabot PRs by a given label
- Consumers would then use this to run separate jobs with a label filter

Something like:

```
# Combine Rust Dependabot PRs
- name: 'Dependabot Batcher'
  uses: Legal-and-General/dependabot-batcher@v1.0.3
    with:
      token: ${{ secrets.YOUR_TOKEN }}
      label: 'rust'
```

and then a separate job for another language/package ecosystem:

```
# Combine JS Dependabot PRs
- name: 'Dependabot Batcher'
  uses: Legal-and-General/dependabot-batcher@v1.0.3
    with:
      token: ${{ secrets.YOUR_TOKEN }}
      label: 'javascript'
```

The default behaviour (in the absence of a label) would be to combine all open PRs, as it does now.
