### ISSUE TITLE
How I can make it to only group certains PRs based on the title?

### ISSUE THREAD

**Issue by mliradelc** [Legal-and-General/dependabot-batcher#38]
Hi, thanks for your awesome tool, I like it a lot.

I have a project that contains a lot of submodules, and Dependabot makes a lot of PRs because each submodule has several dependencies.

Is there a way to tell dependabot-batcher in a job that only select the PRs that contains "X" in the title?

Cheers

Max

**Comment by mliradelc** [comment]
No worries, I figured out myself.

You can use the `paths` option in actions to do that. Example:

```
on:
  pull_request:
    paths:
      - 'path/to/the/module/you/want/to/watch/**'
  push:
    paths:
      - 'path/to/the/module/you/want/to/watch/**'
```
